spring.application.name=ApisSGE
spring.datasource.url=jdbc:mariadb://localhost:3306/erp?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.security.oauth2.client.registration.google.client-id=280037003775-f1efosm3sphdfb796vdomdh50s5u3pcp.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true